name: viral_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  dotted_border: ^3.1.0
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  sign_in_with_apple: ^7.0.1
  firebase_auth: ^6.0.2
  google_sign_in: ^6.2.1
  http: ^1.5.0
  gal: ^2.3.0
  path_provider: ^2.1.1
  image_cropper: ^9.1.0
  cached_network_image: 3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
