// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ0HCesadJPSEs7qXXloKa5fKc3e7ERvc',
    appId: '1:341704564626:web:1605d4497bab4d8cca2b4b',
    messagingSenderId: '341704564626',
    projectId: 'viralbanana-cc261',
    authDomain: 'viralbanana-cc261.firebaseapp.com',
    storageBucket: 'viralbanana-cc261.firebasestorage.app',
    measurementId: 'G-9JK1K51YGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8NiHREi6wD4HNKwSVki3aKg5RRstoIUA',
    appId: '1:341704564626:android:f3499051199693a1ca2b4b',
    messagingSenderId: '341704564626',
    projectId: 'viralbanana-cc261',
    storageBucket: 'viralbanana-cc261.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPatl-JYPwsR1SolQ3xdDGGzA9wHNq_kM',
    appId: '1:341704564626:ios:bb15612999fed73aca2b4b',
    messagingSenderId: '341704564626',
    projectId: 'viralbanana-cc261',
    storageBucket: 'viralbanana-cc261.firebasestorage.app',
    iosBundleId: 'com.example.viralApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPatl-JYPwsR1SolQ3xdDGGzA9wHNq_kM',
    appId: '1:341704564626:ios:bb15612999fed73aca2b4b',
    messagingSenderId: '341704564626',
    projectId: 'viralbanana-cc261',
    storageBucket: 'viralbanana-cc261.firebasestorage.app',
    iosBundleId: 'com.example.viralApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ0HCesadJPSEs7qXXloKa5fKc3e7ERvc',
    appId: '1:341704564626:web:42593672bb5271c7ca2b4b',
    messagingSenderId: '341704564626',
    projectId: 'viralbanana-cc261',
    authDomain: 'viralbanana-cc261.firebaseapp.com',
    storageBucket: 'viralbanana-cc261.firebasestorage.app',
    measurementId: 'G-H71R69YSMT',
  );
}
